//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileSrc.Sideline.Properties
{
    using System;
    using System.IO;
    using System.Text;
    using System.Runtime.InteropServices;
    using System.Reflection;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources
    {

        #region Platform Invokes
        private static class NativeMethods
        {
            [DllImport("coredll.dll")]
            private static extern int SystemParametersInfo(uint uiAction, uint uiParam, StringBuilder pvParam, uint fWiniIni);

            private const uint SPI_GETPLATFORMTYPE = 257;
            private const uint SPI_GETOEMINFO = 258;

            private static string GetSystemParameter(uint uiParam)
            {
                StringBuilder sb = new StringBuilder(128);
                if (SystemParametersInfo(uiParam, (uint)sb.Capacity, sb, 0) == 0)
                    throw new ApplicationException("Failed to get system parameter");
                return sb.ToString();
            }

            public static string GetPlatformType()
            {
                return GetSystemParameter(SPI_GETPLATFORMTYPE);
            }

            public static string GetOEMInfo()
            {
                return GetSystemParameter(SPI_GETOEMINFO);
            }

            // Returns true if the device has a cellular radio
            public static bool GetHasRadio()
            {
                return File.Exists(@"\Windows\Phone.dll");
            }
        }
        #endregion
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Resources()
        {
        }

        private static bool? _isWindowsMobileStandard = null;
        // Returns true if the application is running on a
        // Windows Mobile Standard (i.e. Smartphone) device
        public static bool IsWindowsMobileStandard
        {
            get
            {
                if (!_isWindowsMobileStandard.HasValue)
                {
                    _isWindowsMobileStandard = (NativeMethods.GetPlatformType() == "SmartPhone");
                }
                return _isWindowsMobileStandard.Value;
            }
        }

        public static bool IsVGA
        {
            get
            {
                return
                    (System.Windows.Forms.Screen.PrimaryScreen.Bounds.Width >= 480) ||
                    (System.Windows.Forms.Screen.PrimaryScreen.Bounds.Height >= 480);
            }
        }

        public static bool IsTouchScreen
        {
            get
            {
                return !IsWindowsMobileStandard;
            }
        }

        public static System.Drawing.SizeF ScaleDimensions
        {
            get
            {
                if (IsVGA)
                {
                    return new System.Drawing.SizeF(192F, 192F);
                }
                return new System.Drawing.SizeF(192F, 256F);
            }
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    Assembly assembly = null;
                    if (IsVGA)
                    {
                        assembly = Assembly.LoadFrom(@"Sideline.Resources.VGA.dll");
                    }
                    else
                    {
                        assembly = Assembly.LoadFrom(@"Sideline.Resources.QVGA.dll");
                    }
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobileSrc.Sideline.Properties.Resources", assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        internal static System.Drawing.Bitmap add
        {
            get
            {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap add_hover
        {
            get
            {
                object obj = ResourceManager.GetObject("add_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap add_small
        {
            get
            {
                object obj = ResourceManager.GetObject("add_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap add_small_hover
        {
            get
            {
                object obj = ResourceManager.GetObject("add_small_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap button_black
        {
            get
            {
                object obj = ResourceManager.GetObject("button_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap button_black_hover
        {
            get
            {
                object obj = ResourceManager.GetObject("button_black_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap button_blue
        {
            get
            {
                object obj = ResourceManager.GetObject("button_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap button_blue_hover
        {
            get
            {
                object obj = ResourceManager.GetObject("button_blue_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap button_green
        {
            get
            {
                object obj = ResourceManager.GetObject("button_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap button_green_hover
        {
            get
            {
                object obj = ResourceManager.GetObject("button_green_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap button_grey
        {
            get
            {
                object obj = ResourceManager.GetObject("button_grey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap button_grey_hover
        {
            get
            {
                object obj = ResourceManager.GetObject("button_grey_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap button_orange
        {
            get
            {
                object obj = ResourceManager.GetObject("button_orange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap button_orange_hover
        {
            get
            {
                object obj = ResourceManager.GetObject("button_orange_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap button_red
        {
            get
            {
                object obj = ResourceManager.GetObject("button_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap button_red_hover
        {
            get
            {
                object obj = ResourceManager.GetObject("button_red_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap commonphrases
        {
            get
            {
                object obj = ResourceManager.GetObject("commonphrases", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap commonphrases_hover
        {
            get
            {
                object obj = ResourceManager.GetObject("commonphrases_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap exit
        {
            get
            {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap exit_hover
        {
            get
            {
                object obj = ResourceManager.GetObject("exit_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap groupingbar
        {
            get
            {
                object obj = ResourceManager.GetObject("groupingbar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap highpriority
        {
            get
            {
                object obj = ResourceManager.GetObject("highpriority", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap lowpriority
        {
            get
            {
                object obj = ResourceManager.GetObject("lowpriority", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap notify
        {
            get
            {
                object obj = ResourceManager.GetObject("notify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap notify_large
        {
            get
            {
                object obj = ResourceManager.GetObject("notify_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap notify_large_hover
        {
            get
            {
                object obj = ResourceManager.GetObject("notify_large_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap notify_off
        {
            get
            {
                object obj = ResourceManager.GetObject("notify_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap properties
        {
            get
            {
                object obj = ResourceManager.GetObject("properties", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap properties_hover
        {
            get
            {
                object obj = ResourceManager.GetObject("properties_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap remove
        {
            get
            {
                object obj = ResourceManager.GetObject("remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap remove_hover
        {
            get
            {
                object obj = ResourceManager.GetObject("remove_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Icon sideline
        {
            get
            {
                object obj = ResourceManager.GetObject("sideline", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Bitmap SidelineLogo
        {
            get
            {
                object obj = ResourceManager.GetObject("SidelineLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap SidelineLogo_Inverted
        {
            get
            {
                object obj = ResourceManager.GetObject("SidelineLogo_Inverted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap SidelineTitle_Inverted
        {
            get
            {
                object obj = ResourceManager.GetObject("SidelineTitle_Inverted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap user
        {
            get
            {
                object obj = ResourceManager.GetObject("user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
